server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nihek-db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition:
    stream:
      bindings:
        userRegisteredBinding-out-0:
          binder: kafka_default
          destination: event.user-registered
          useNativeDecoding: true
      binders:
        kafka_default:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    default:
                      consumer:
                        configuration:
                          session.timeout.ms: 10000
                          max.poll.records: 10
                      producer:
                        producer:
                          compressionType: gzip
                          configuration:
                            max.request.size: 10485760
                    binder:
                      autoAddPartitions: true
                      autoCreateTopics: true
                      requiredAcks: -1
                      minPartitionCount: 3
                      replicationFactor: 1
                      serdeError: logAndContinue
                      brokers: localhost:9092





jwt:
  secret:
    token: dbgljbvbaoebvbsZkvbpsabvpibdclkvbdspifvahbcdisvfwvfouyewvbalfibeslfvafbcldasbpfiewaubfbeluafbeafbkjlsbafiaew

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html

