server:
  port: 8083
spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db
    username: postgres
    password: 1234

  cloud:
    function:
      definition: userRegisteredBinding
    stream:
      bindings:
        userRegisteredBinding-in-0:
          binder: kafka_default
          destination: event.user-registered
          useNativeDecoding: true
      binders:
        kafka_default:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    default:
                      consumer:
                        configuration:
                          session.timeout.ms: 10000
                          max.poll.records: 10
                      producer:
                        compressionType: gzip
                        configuration:
                          max.request.size: 10485760
                    binder:
                      brokers: localhost:9092
                      autoAddPartitions: true
                      autoCreateTopics: true
                      requiredAcks: -1
                      minPartitionCount: 3
                      replicationFactor: 1
                      serdeError: logAndContinue

mailgun:
  api: e96b4f3820e8e7509313fddef7705111-d8df908e-08ad6983
  domain: nihek.com